//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tech_Forum.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PostEntity : DbContext
    {
        public PostEntity()
            : base("name=PostEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
      //  public virtual DbSet<Domain_Table> Domain_Table { get; set; }
       // public virtual DbSet<Technology_Table> Technology_Table { get; set; }
        public virtual DbSet<Subscriber_Table> Subscriber_Table { get; set; }
        public virtual DbSet<Post_Table> Post_Table { get; set; }
    }
}
