//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tech_Forum.Models
{
    using System;
    using System.Collections.Generic;
    
    /*public partial class Technology_Table
    {
        public int tid { get; set; }
        public string technology { get; set; }
        public int did { get; set; }
    
        public virtual Domain_Table Domain_Table { get; set; }
    }*/
}
