//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tech_Forum.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question_Bank_Table
    {
        public int QuestionID { get; set; }
        public string Question { get; set; }
        public string Option1 { get; set; }
        public string Option2 { get; set; }
        public string Option3 { get; set; }
        public string Option4 { get; set; }
        public string CorrectAnswer { get; set; }
        public int did { get; set; }
        public int tid { get; set; }
    
        public virtual Domain_Table Domain_Table { get; set; }
        public virtual Technology_Table Technology_Table { get; set; }
    }
}
