//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tech_Forum.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test_Table
    {
        public int TestId { get; set; }
        public string UserId { get; set; }
        public string SelectedOptions { get; set; }
        public int Score { get; set; }
        public int DomainID { get; set; }
        public int TechnologyID { get; set; }
    
        public virtual Domain_Table Domain_Table { get; set; }
        public virtual Subscriber_Table Subscriber_Table { get; set; }
        public virtual Technology_Table Technology_Table { get; set; }
    }
}
